# Generated by Django 4.1.5 on 2023-02-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0004_clientesmodel_ordenesmodel_pagosmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordenesmodel',
            old_name='client_id',
            new_name='cliente_id',
        ),
        migrations.AlterField(
            model_name='ordenesmodel',
            name='observacion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='boletaspagomodel',
            table=None,
        ),
    ]
